{% set name = "multipers" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a6c0e7f2825af24c3e743dd4aeea5afc859d70ea7f3705c80d6380cd5d9476d

build:
  script: |
    export CMAKE_GENERATOR=Ninja
    {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps --config-settings=cmake.args="${CMAKE_ARGS}"
  number: 0
  skip: true  # [py<=39]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - pip
    - python-build
    - wheel
    - scikit-build-core
    - ninja
    - cmake >=3.27
  host:
    - python
    - numpy >=2
    - cython >=3
    - python-build
    - scikit-build-core
    - wheel
    - pip
    - tbb
    - tbb-devel
    - libboost-devel
    - cgal-cpp 
    - gmp         # [not win]
    - mpfr        # [not win]
    - llvm-openmp                            # [osx]
    - libgomp                                # [linux]
    - intel-openmp                           # [win]
    - eigen
  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - gudhi >=3.8
    - tqdm
    - scipy
    - joblib
    - matplotlib-base
    - scikit-learn
    - pot
    - libgmp      # [win]
    - mpfr        # [win]
    - llvm-openmp                            # [osx]
    - libgomp                                # [linux]
    - intel-openmp                           # [win]


test:
  imports:
    - multipers
  requires:
    - pip
  commands:
    - pip install pykeops filtration-domination --upgrade
    - pip check
about:
  home: https://davidlapous.github.io/multipers/
  summary: Multiparameter Topological Persistence for Machine Learning
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DavidLapous
