{% set name = "multipers" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63b48a0d020457653f436d55881c9d679f4972029534047bcc5b438a9a763b07

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<=39]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
  host:
    - python
    - numpy >=2
    - cython >=3
    - setuptools
    - pip
    - tbb
    - tbb-devel
    - libboost-devel
  run:
    - python
    - tbb
    - numpy
    - gudhi >=3.8
    - tqdm
    - scipy
    - joblib
    - matplotlib-base
    - scikit-learn
    - pot


test:
  imports:
    - multipers
  requires:
    - pip
  commands:
    - pip install pykeops filtration-domination --upgrade
    - pip check
about:
  home: https://davidlapous.github.io/multipers/
  summary: Multiparameter Topological Persistence for Machine Learning
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DavidLapous
